CREATE TABLE users (
  uid SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  email VARCHAR(255),
  date_created DATE,
  last_login DATE
);

CREATE TABLE machines (
  mid SERIAL PRIMARY KEY,
  machine_name VARCHAR(255) UNIQUE,
  machine_line VARCHAR(255),
  url VARCHAR(255),
  type VARCHAR(20),
  speed SMALLINT,
  timetoscan SMALLINT
);

CREATE TABLE incpec_multi4 (
    iid UUID PRIMARY KEY,
    machine_id INT REFERENCES machines(mid),
    inspected INT,
    rejected INT,
    mcf_other INT,
    mcf_compact INT,
    mcf_blister INT,
    mcf_drawn INT,
    mcf_sideobject INT,
    mcf_density INT,
    mcf_thin INT,
    mcf_mark INT,
    csbclo_registration INT,
    Csbclo_lineoverfinish INT,
    Csbclo_internalblister1 INT,
    Csbclo_Internalblister2 INT,
    Csbclo_externalblister INT,
    Csbclo_scalyfinish INT,
    Csbclo_Sugarytop INT,
    Csbclo_overpressed1 INT,
    Csbclo_overpressed2 INT,
    Csbclo_Unrolled INT,
    Csbclo_unfilledfinish1 INT,
    Csbclo_unfilledfinish2 INT,
    Csbclo_unfilledfinish3 INT,
    Csbclo_internalblackdefect INT,
    Csbclo_surfaceblackdefect INT,
    Csbclo_externalblackdefect INT,
    spike_other INT,
    spike_stone INT,
    spike_blister INT,
    spike_drawn INT,
    spike_density INT,
    spike_lightbottom INT,
    spike_chockedneck INT,
    spike_mark INT,
    stress_Stress INT,
    stress_error INT,
    stress_blackimage INT
);