CREATE TABLE users (
  uid SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  email VARCHAR(255),
  date_created DATE,
  last_login DATE,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
);

CREATE TABLE machines (
  uid SERIAL PRIMARY KEY,
  machine_name VARCHAR(255) UNIQUE,
  machine_line VARCHAR(255),
  url VARCHAR(255),
  type VARCHAR(20),
  speed SMALLINT,
  timetoscan SMALLINT,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
);

CREATE TABLE multi4 (
    uid UUID PRIMARY KEY,
    machine_id INT REFERENCES machines(uid),
    inspected INT,
    rejected INT,
    mcf_reject INT,
    csbc_reject INT,
    spike_reject INT,
    stress_reject INT,
    mcf_other INT,
    mcf_compact INT,
    mcf_blister INT,
    mcf_drawn INT,
    mcf_sideobject INT,
    mcf_density INT,
    mcf_thin INT,
    mcf_mark INT,
    csbc_registration INT,
    csbc_lineoverfinish INT,
    csbc_internalblister1 INT,
    csbc_Internalblister2 INT,
    csbc_externalblister INT,
    csbc_scalyfinish INT,
    csbc_Sugarytop INT,
    csbc_overpressed1 INT,
    csbc_overpressed2 INT,
    csbc_Unrolled INT,
    csbc_unfilledfinish1 INT,
    csbc_unfilledfinish2 INT,
    csbc_unfilledfinish3 INT,
    csbc_internalblackdefect INT,
    csbc_surfaceblackdefect INT,
    csbc_externalblackdefect INT,
    spike_other INT,
    spike_stone INT,
    spike_blister INT,
    spike_drawn INT,
    spike_density INT,
    spike_lightbottom INT,
    spike_chockedneck INT,
    spike_mark INT,
    stress_Stress INT,
    stress_error INT,
    stress_blackimage INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE mcal4 (
    uid UUID PRIMARY KEY,
    machine_id INT REFERENCES machines(uid),
    inspected INT,
    rejected INT,
    sidewall_total reject INT,
    dim_total_reject INT,
    stress_total_reject INT,
    lowcontrast_total_reject INT,
    sidewall_other INT,
    sidewall_compact INT,
    sidewall_blister INT,
    sidewall_drawn INT,
    sidewall_sideobject INT,
    sidewall_density INT,
    sidewall_thin INT,
    sidewall_birdswing INT,
    sidewall_wings INT,
    dim_Verticality INT,
    dim_Diameter INT,
    dim_Height INT,
    dim_Verticality1 INT,
    dim_Verticality2 INT,
    dim_Verticality3 INT,
    dim_Diameter1 INT,
    dim_Diameter2 INT,
    dim_Diameter3 INT,
    dim_Diameter4 INT,
    dim_Diameter5 INT,
    dim_Diameter6 INT,
    dim_Height1 INT,
    dim_Height2 INT,
    lowcontrast_Transition INT,
    lowcontrast_nolearningparameters INT,
    lowcontrast_deformation INT,
    lowcontrast_error INT,
    lowcontrast_blackimage INT,
    stress_stress INT,
    stress_error INT,
    stress_blackimage INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE mx4 (
    uid UUID PRIMARY KEY,
    machine_id INT REFERENCES machines(uid),
    total_inspected INT,
    total_rejected INT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ  
);

CREATE TABLE mold (
    uid UUID PRIMARY KEY,
    machine_id INT REFERENCES machines(uid),
    inspected INT,
    rejected INT,
    lnmc_autoreject INT,
    boc_internaldiameter INT,
    boc_externaldiameter INT,
    lnm_autoreject INT,
    dimbag_hight INT,
    dimbag_diameter1 INT,
    dimbag_diameter2 INT,
    dimbag_diameter3 INT,
    dimbag_diameter4 INT,
    dimbag_diameter5 INT,
    dimbag_diameter6 INT,
    dimbag_diameter7 INT,
    dimbag_diameter8 INT,
    dimbag_slope INT,
    dimbag_dip INT,
    dimbag_bentneck INT,
    dimbag_localdefect INT,
    dimbag_totaldiameter INT,
    plugservo_internalmax INT,
    plugservo_internalmin INT,
    plugservo_choquedneck INT,
    plugservo_externalmax INT,
    plugservo_externalmin INT,
    plugservo_toohigh INT,
    plugservo_toolow  INT,
    plugservo_brokenneck INT,
    plugindexer_defect INT,
    leak_defect INT,
    check_gla1ch1 INT,
    check_gla1ch2 INT,
    check_gla1ch3 INT,
    check_gla1ch4 INT,
    check_gla1ch5 INT,
    check_gla1ch6 INT,
    check_gla1ch7 INT,
    check_gla1ch8 INT,
    check_gla2ch1 INT,
    check_gla2ch2 INT,
    check_gla2ch3 INT,
    check_gla2ch4 INT,
    check_gla2ch5 INT,
    check_gla2ch6 INT,
    check_gla2ch7 INT,
    check_gla2ch8 INT,
    check_gla3ch1 INT,
    check_gla3ch2 INT,
    check_gla3ch3 INT,
    check_gla3ch4 INT,
    check_gla3ch5 INT,
    check_gla3ch6 INT,
    check_gla3ch7 INT,
    check_gla3ch8 INT, 
    ovality_lev1min INT,
    ovality_lev1max INT,
    ovality_lev1ovality INT,
    ovality_lev2min INT,
    ovality_lev2max INT,
    ovality_lev2ovality INT,
    ovality_total1 INT,
    ovality_total2 INT,  
    csb_glanum1 INT,
    csb_glanum2 INT,
    csb_glanum3 INT,
    csb_glanum4 INT,
    thickness_level1 INT,
    thickness_level2 INT,  
    thickness_level3 INT,
    thickness_level4 INT,
    nci_camera1 INT,
    nci_camera1z1 INT,
    nci_camera1z2 INT,
    nci_camera1z3 INT,
    nci_camera1z4 INT,
    nci_camera2 INT,
    nci_camera2z1 INT,
    nci_camera2z2 INT,
    nci_camera2z3 INT,
    nci_camera2z4 INT,
    nci_camera3 INT,
    nci_camera3z1 INT,
    nci_camera3z2 INT,
    nci_camera3z3 INT,
    nci_camera3z4 INT,
    nci_total1 INT,
    nci_total2 INT,
    nci_total3 INT,
    atlas_vcheck1 INT,
    atlas_vcheck2 INT,
    atlas_vcheck3 INT,
    atlas_vcheck4 INT,
    atlas_hocheck1 INT,
    atlas_hocheck2 INT,
    atlas_hocheck3 INT,
    atlas_hocheck4 INT,
    atlas_hocheck5 INT,
    atlas_hocheck6 INT,
    atlas_hocheck7 INT,
    atlas_hocheck8 INT,
    atlas_scheck1 INT,
    atlas_scheck2 INT,
    atlas_scheck3 INT,
    atlas_hcheck1 INT,
    atlas_hcheck2 INT,
    atlas_hcheck3 INT,
    atlas_error INT,
    atlas_totalvcheck INT,
    atlas_totalhcheck INT,
    atlas_totalscheck INT,
    atlas_totalhcheck INT
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE alarms(
  uid UUID PRIMARY KEY,
  machine_id INT REFERENCES machines(uid),
  alarm_date TIMESTAMPTZ,
  codetype INT,
  codecatagorie INT,
  codesubcat INT,
  label text,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
);